version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sary_assignment
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/

  cache:
    image: redis
    ports:
      - '6379:6379'
    command: ['--requirepass "secret"']
    volumes:
      - cache:/data

  api:
    image: ibrahimhussein/reservations
    ports:
      - '8080:8080'
    depends_on:
      - db
      - cache

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin1234
#    ports:
#      - '5050:80'
#    restart: always
#    volumes:
#      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
  cache:
